spring:
  application:
    name: s3bucket

  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

aws:
  s3:
    bucket:
      name: elice-project2-team4
      stack.auto: false
      region: ap-northeast-2
      url: https://elice-project2-team4.s3.ap-northeast-2.amazonaws.com
      credentials:
        accessKey: {{ iam access key }}
        secretAccessKey: {{ iam secret access key }}

